spring:
  datasource:
    password:
    url:  jdbc:mysql://localhost:3306/employee_manager_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true